# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build and Publish NNI Package

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Microsoft NNI
      uses: actions/checkout@v2
      with:
        repository: microsoft/nni
    - name: Fetch all tags
      run: |
        git fetch --tags --depth=1 origin +refs/tags/*:refs/tags/*
        git describe --tags --abbrev=0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        cd deployment/pypi
        sed -ie "s/name = 'nni'/name = 'nni-daily'/" setup.py
        sed -ie 's/node scripts\/build.js/node --max-old-space-size=4096 scripts\/build.js/' ../../src/webui/package.json
        make version_ts=true build
        twine upload dist/*
